### ISSUE TITLE
Release 0.6.0 does not install properly with pip

### ISSUE THREAD

**Issue by FredrikAppelros** [uber/vertica-python#111]
Trying to import the latest release of vertica-python fails due to some dependencies are missing from `setup.py`:

	Python 2.7.11 (default, Jan 21 2016, 16:14:29) 
	[GCC 4.8.4] on linux2
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import vertica_python
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/home/fredrik/.pyenv/versions/vertica-test/lib/python2.7/site-packages/vertica_python/__init__.py", line 3, in <module>
	    from vertica_python.vertica.connection import Connection
	  File "/home/fredrik/.pyenv/versions/vertica-test/lib/python2.7/site-packages/vertica_python/vertica/connection.py", line 10, in <module>
	    from builtins import str
	ImportError: No module named builtins

Seem like `future` has been added as a dependency, but only to the `requirements.txt` file, but not the actual list of dependencies in `setup.py`.

**Comment by alexjikim** [comment]
sweet, thanks for the pull request
